android-tools: use patchdir parameter to apply patches
* helps to apply the patches for correct git repo
* split remove-selinux-android.patch into 2, because devtool modify fails to apply
  it across 2 different git repositories:
ERROR: Command Error: 'sh -c 'PATCHFILE="remove-selinux-android.patch" git -c user.name="OpenEmbedded" -c user.email="oe.patch@oe" commit -F /tmp/tmpvn7yf20j --author="Sergio Schvezov <sergio.schvezov@canonical.com>" --date="Wed, 7 Sep 2016 12:58:47 +0300"'' exited with 0  Output:
On branch devtool
Changes not staged for commit:
        modified:   system/core (modified content)
        modified:   system/extras (modified content)

no changes added to commit
ERROR: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /OE/build/owpb/webos-ports/tmp-glibc/work/aarch64-webos-linux/android-tools/5.1.1.r37-r0/devtooltmp-7qrccor9/temp/log.do_patch.8643
NOTE: Tasks Summary: Attempted 3 tasks of which 0 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory
ERROR: Extracting source for android-tools failed

* similarly with remove-bionic-android.patch

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>